### ISSUE TITLE
Notification: after saving preferences, it redirects to profile page

### ISSUE THREAD

**Issue by Bhavaninalla** [FightPandemics/FightPandemics#1805] opened 2020-11-12 22:37 UTC
URL : https://featurenotifications.fightpandemics.xyz/
Click user edit profile icon
Click Edit notifications
Click Save changes button
After clicking save changes it redirects to the user profile page instead of staying on the same page.
![ezgif-4-39fdbe6700dc](https://user-images.githubusercontent.com/72236992/99004566-28334180-24f4-11eb-9a42-0c04d64538bc.gif)

**Comment by ddveloper** [comment] 2020-11-13 04:12
@Bhavaninalla I noticed it's the same behavior as the other 2 settings, `Edit Account` and `Edit Profile`, right?

**Comment by mannykary** [comment] 2020-11-13 04:27
@CamilaArias @nfranklin9 what should the expected behavior be here? As @ddveloper mentioned, the behavior is the same as when saving in "Edit Account" and "Edit Profile", so saving on this page should mimic that behavior right?

**Comment by Bhavaninalla** [comment] 2020-11-13 04:34
Yes

**Comment by nfranklin9** [comment] 2020-11-13 20:43
@mannykary Yes, it should mimic that behavior. But can this be changed before the staging deadline this weekend?

**Comment by mannykary** [comment] 2020-11-14 01:40
Then this is not a defect since the behavior is as expected. Closing the ticket.

**Closed as completed** 2020-11-14 01:41 UTC
Labels: f_notification
