### ISSUE TITLE
"View Profile" Button is buggy

### ISSUE THREAD

**Issue by WillHiggs** [FightPandemics/FightPandemics#1522] opened 2020-09-14 00:04 UTC
When I hover my mouse over the "view my profile" button after creating a profile in the staging environment on my desktop, the text on the button. What could be causing this issue and what are some steps I or someone else could take to address it?

**Comment by kterry1** [comment] 2020-09-14 01:22
Hi, @WillHiggs. Could you provide more details here? When you say "the text on the button", I'm not sure what the issue is. Please add a screenshot or screen recording or provide steps to reproduce the issue. Feel free to slack me if you have any questions on this.

Thanks!

**Comment by kterry1** [comment] 2020-09-16 03:33
Closing out. No further details provided here from OP. Reached out to OP in Slack as well.

**Closed as completed by kterry1** 2020-09-16 03:33 UTC
