### ISSUE TITLE
Text Overlapping into the close button(Mobile Version)

### ISSUE THREAD

**Issue by SinghRomika** [FightPandemics/FightPandemics#2265] opened 2021-03-08 19:33 UTC
**The text is overlapping into the close button for several translated languages in the mobile version:**

![Screenshot 2021-03-02 161221](https://user-images.githubusercontent.com/78573508/110371555-fe051280-8001-11eb-8616-7623619726c6.gif)

**Comment by emanuelquerty** [comment] 2021-03-08 23:38
Could you please add the steps to reproduce this as I'm not able to reproduce this in [Staging](https://staging.fightpandemics.work/) ?

<img width="668" alt="Screen Shot 2021-03-08 at 4 39 37 PM" src="https://user-images.githubusercontent.com/30244286/110396270-f4dd6b00-802c-11eb-8376-7e51c9584df5.png">

**Comment by SinghRomika** [comment] 2021-03-09 16:41
@emanuelquerty Build URL: https://featureprofile-redesign-user-profile-car.fightpandemics.xyz. Please wait a few minutes for the deployment to complete.

**Comment by SinghRomika** [comment] 2021-03-09 18:08
@emanuelquerty Seems like the issue is already fixed in the feature build. But if you would still like to look into i am sharing the Build link :  https://feature2233-overlapping-text.fightpandemics.xyz

**Comment by emanuelquerty** [comment] 2021-03-10 21:44
@SinghRomika thanks for letting me know it's been fixed in the feature build. Do you want to close this issue then?
Thanks!

**Closed as completed** 2021-03-11 00:26 UTC
Labels: Mobile Web, UI, P3, Translation
