### ISSUE TITLE
Profile -> Org name -> Create POST -> Org POST -> BLANK page is displayed.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#867] opened 2020-06-27 16:44 UTC
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/pwd
3. Navigate Profile -> Org Name(created earlier) -> Create POST icon -> Create Posting as 'Organisation'

Issue# You will observe BLANK page is displayed as shown in below GIF.

https://share.getcloudapp.com/6qu2E8zA

Please note, I am able to create 'Organisation' note from my individual user profile.

**Comment by idjevm** [comment] 2020-06-27 16:57
@kylejvh this is referring to that change you did yesterday here -> https://github.com/FightPandemics/FightPandemics/blob/master/client/src/components/CreatePost/CreatePost.js#L61

Mind taking a look?

**Comment by joshmorel** [comment] 2020-06-27 18:13
I think the issue is user is undefined sometimes.

We have this CreatePost component used in 3 places - so I think one of these is not correct. 

![image](https://user-images.githubusercontent.com/10546720/85929148-5fc08a80-b880-11ea-94a1-81fca55a7333.png)

**Comment by joshmorel** [comment] 2020-06-27 18:36
It's the OrganizationProfile one that is the issue. Posting from Feed.js or Profile.js is okay. @kylejvh or @nr431207 however feels like taking this on and can fix by today/tomorrow assign yourself. If no one's assigned by tomorrow I will fix.

**Comment by rabbi08** [comment] 2020-06-27 20:36
@vikjoshi FYI

**Comment by kylejvh** [comment] 2020-06-27 23:45
Trying to reproduce from the staging link above doesn't work for me but I'm taking a look and I'll try to fix it.

**Comment by kylejvh** [comment] 2020-06-28 00:25
`OrganizationProfile` and `Profile` use a lot of the same code, yet `OrganizationProfile` does not know about the user, and `Profile` does. This is why this breaks. I'm working on fixing it so that the right information is passed, but we should make `Profile` work in a way that it can display information for both organizations and users.

**Comment by kylejvh** [comment] 2020-06-28 00:51
Since there are a lot of common components that require information off of user state, maybe we should wrap the entire application with `withUserContext` or Redux `connect()`. This would help fix a lot of the blank screen issues we've been having with `CreatePost` and `Profile`. @robinv85 @joshmorel 
Thoughts?

**Comment by joshmorel** [comment] 2020-06-28 01:24
@kylejvh I agree. We still haven't decided on state management approach but since current user is in redux that makes sense for this component for now

**Comment by joshmorel** [comment] 2020-06-29 14:54
Resolved by #885

**Closed by joshmorel** 2020-06-29 14:54 UTC
Labels: High Priority, MVP - Critical, Organization Profile, Post, bug
