### ISSUE TITLE
fix layout on landing view

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics#288] opened 2020-05-11 02:29 UTC
flow
- go to https://staging.fightpandemics.work/

layout issues

1 - logo is not aligned on the left with the title (may be a navbar problem)
2 - spacing below logo 
2 - missing title
3 - spacing between title and subtitle
4 - spacing on lines on subtitle
5 - no rounded borders in the blue box
6 - no left margin
7 - incorrect font styles used in the blue box

<img width="2020" alt="Screenshot 2020-05-11 at 03 26 37" src="https://user-images.githubusercontent.com/29093946/81518977-90cc1680-9337-11ea-8c15-19716e1f9c79.png">

Styles should be pixel perfect:
<img width="857" alt="Screen Shot 2020-05-10 at 11 14 36 PM" src="https://user-images.githubusercontent.com/42228386/81529593-0625f000-9314-11ea-9a4f-e220940b9b22.png">

iMac, Chrome

Reference:
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

**Comment by nadinejuraschek** [comment] 2020-05-11 03:10
So the padding for the header / navigation bar has to be changed? That will change it for all pages. Just want to make sure that's alright before I start working on this!

**Comment by stavares843** [comment] 2020-05-11 03:15
cc @anniegiang

**Comment by anniegiang** [comment] 2020-05-11 05:27
> So the padding for the header / navigation bar has to be changed? That will change it for all pages. Just want to make sure that's alright before I start working on this!

Not sure... But for this issue specifically it looks like there's some padding/margin on the left of the blue box. Maybe we could set either of them to be 0 so that it's right next to the left side.

**Comment by anniegiang** [comment] 2020-05-11 06:17
Ah ok so I just played with the styles in the console and removed the margin added on the right and left side of `<main>`. I also removed the unnessccary rounded borders to the box:

<img width="1012" alt="Screen Shot 2020-05-10 at 11 16 09 PM" src="https://user-images.githubusercontent.com/42228386/81529707-3d949c80-9314-11ea-98cb-cc6368a66a69.png">

**Comment by tiagocostasilva** [comment] 2020-05-29 08:02
Hello Team,
this issue is still not complete. Please check the below image. The text is still missing:

![image](https://user-images.githubusercontent.com/45389561/83236233-16025880-a18b-11ea-9b9d-69c85f1a2482.png)

Thanks,
Tiago

**Comment by tiagocostasilva** [comment] 2020-05-29 08:03
Hello Team,
this issue is still not complete. Please check the below image. The text is still missing:

![image](https://user-images.githubusercontent.com/45389561/83236233-16025880-a18b-11ea-9b9d-69c85f1a2482.png)

Thanks,
Tiago

**Comment by anniegiang** [comment] 2020-05-29 19:16
Ok good to know. We actually discussed about this in the previous PR because there were conflicting designs showing different things. If I remember correctly some of the things you point out this time did not exist the last time we worked on this. I think engineers need to be better updated on design changes such as this to prevent possible regression.

**Comment by tiagocostasilva** [comment] 2020-05-30 14:49
Hello @anniegiang. My user would be @tiagocostasilva instead of @TiagoaTavares (this is the other Tiago :D ) but not worries 
From what i see when @stavares843 oppened this issue, the things i mention here were already identified, so i think this details were missed. This should not be skipped from the MVP.

**Comment by snowiesuet** [comment] 2020-05-30 18:22
@tiagocostasilva this page is updated, its in staging now

**Comment by tiagocostasilva** [comment] 2020-06-07 14:10
@snowiesuet is there something missing on this issue?

**Comment by robinv85** [comment] 2020-06-12 18:42
@tiagocostasilva @snowiesuet is this still not fixed?

**Comment by ppagarawal** [comment] 2020-06-12 19:40
@robinv85 I believe that this is fixed with better UI. @idjevm has made the changes as per the design. We need to close it without impacting the changes @idjevm has made.

**Comment by idjevm** [comment] 2020-06-20 07:44
This issue seems to be fixed. Closing this for now.

**Closed by idjevm** 2020-06-20 07:44 UTC
Labels: Difficulty - Easy, FRONTEND, HomePage, MVP - Release 1, bug, help wanted
