### ISSUE TITLE
"Unable to EDIT post" AND "The Post is displayed as 'edited' after user 'Like' the post"

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1952] opened 2020-11-26 22:41 UTC
1. Open FP app and login as valid username and password
2. Create a post and like it -> navigate to 'Back'

Issue: You will observe that the post is displayed as 'edited' post even though it is NOT edited.
Refer below GIF
![ezgif com-gif-maker](https://user-images.githubusercontent.com/67168400/100395318-74ab7080-300e-11eb-9c70-d84b3af9cfdb.gif)

**Comment by aditilamkhede** [comment] 2020-11-26 23:09
@rabbi08 Also, when I tried to edit the post, it doesn't save the changes.

**Comment by rabbi08** [comment] 2020-11-26 23:17
> @rabbi08 Also, when I tried to edit the post, it doesn't save the changes.

great catch. Thanks @aditilamkhede 
@ddveloper 
This is critical issue.

**Comment by ddveloper** [comment] 2020-11-27 00:16
Hi @aditilamkhede @rabbi08 , could you send the link you use to run the test? I saw it happen on https://staging.fightpandemics.work/ on my old post, then I delete that and create a new one, I am able to edit it now, would you also try create a new post to see if you can edit? (and double check again on the old post you cannot edit it)

**Comment by rabbi08** [comment] 2020-11-27 01:09
@ddveloper 
Please see below GIF
![ezgif com-video-to-gif 37](https://user-images.githubusercontent.com/67168400/100400080-32405e80-3023-11eb-8213-fc1e9a5140c0.gif)

**Comment by rabbi08** [comment] 2020-11-27 01:21
@ddveloper 
Please see below GIF this was created and edited on Nov 10 and it was working fine.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/67168400/100400568-fe663880-3024-11eb-94ef-d712b0497536.gif)

Also see the screenshot, the value for 'timeline visibility' is not valid.
![image](https://user-images.githubusercontent.com/67168400/100400557-f4dcd080-3024-11eb-8082-ba60d7d2bf12.png)

**Comment by rabbi08** [comment] 2020-11-27 02:07
If the  new or old .., post visibility is ‘forever’ it is working fine but not for other time visibility..,

**Comment by ddveloper** [comment] 2020-11-27 05:06
@Zaydme  the [moment.updateLocale(i18n.language](https://github.com/FightPandemics/FightPandemics/blob/addeb75f497935b1a6c34d167685086238e77137/client/src/assets/data/formToPostMappings.js#L14) is causing some problem, to reproduce the issue, 
```
1. create a new post with selection "for one week", post it.
2. edit the post using the `...` menu, you'll see the expire selection change to `days` <-- should be "for one week"
3. try to save any changes other than this expire selection causes a axios.patch error (Schema accept `day`)
```
![image](https://user-images.githubusercontent.com/44758313/100412891-c235d680-302a-11eb-9390-1b1cbd36a863.png)

**Comment by Zaydme** [comment] 2020-11-27 12:50
@ddveloper the solution to that is to only localize the displayed value of the select menu, and not the option value.

**Comment by ddveloper** [comment] 2020-11-27 18:35
Hi @rabbi08 , please have check on this link https://feature1952-cannoteditpostformultiexpire.fightpandemics.xyz/

**Comment by rabbi08** [comment] 2020-11-27 23:15
@ddveloper @Zaydme 
Verified the fix on the feature branch, it is working fine.
Thanks
Refer below GIF
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/67168400/100488494-907d4800-30dc-11eb-84f2-8d3c7ce58304.gif)

**Comment by ddveloper** [comment] 2020-11-28 00:02
Thanks @rabbi08

**Comment by ddveloper** [comment] 2020-11-28 00:40
repoen for the 2nd part - `edited` issue

**Comment by Zaydme** [comment] 2020-11-28 13:02
For this I think we need a new `isEdited: Boolean` field.
Since the updatedAt we use now gets also updated when the post gets liked (and reported soon).

**Comment by ddveloper** [comment] 2020-11-29 17:17
@rabbi08 @aditilamkhede this is ready for review at https://feature1952-edited-after-like.fightpandemics.xyz/ thanks!

**Comment by rabbi08** [comment] 2020-11-30 21:43
@ddveloper 
Existing in STG again hence re-opening. Thanks

**Comment by rabbi08** [comment] 2020-11-30 22:47
@ddveloper 
verified the fix on 
https://feature1952-cannot-edit-posts.fightpandemics.xyz/
 it is working fine.

@Zaydme lets review and merge this into STG

**Comment by sheeba1** [comment] 2020-11-30 22:53
original observation on STG, unable to edit  a post. 

when visibility is set to month/week,unable to edit post

**Comment by ddveloper** [comment] 2020-12-01 00:20
workaround #1998  merged in staging

**Comment by Zaydme** [comment] 2020-12-01 00:57
Closing this now, reopening if ever happens again.

**Closed as completed by Zaydme** 2020-12-01 00:57 UTC
Labels: Post, High Priority
