### ISSUE TITLE
'FightyPandemiccs' logo on 'Individual User profile create' page should be clickable.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1153] opened 2020-07-14 05:19 UTC
1. Open "staging.fightpandemics.work"
2. Sign up as new user say 'Linkedin User'
3. On User profile creation page, scroll over 'FP' logo present in top left corner.

Issue: you will observe that FP logo is NOT clickable

**Comment by joshmorel** [comment] 2020-07-16 16:55
Hi @rabbi08 - this does relate to my response to @idjevm  here: https://github.com/FightPandemics/FightPandemics/pull/1163#issuecomment-659019138

As well as the issue I created here #1164 

I assume you are referring to this logo:

![image](https://user-images.githubusercontent.com/10546720/87699455-e1f6ed00-c762-11ea-8453-983f54ac34c3.png)


As best as I can explain and understand, what's happening is after authorizing OAuth is we are redirected to `/create-profile` in this `RouteWithSubRoutes.js` component due to some condition (I'd need to look it up) - but the same thing will redirect you back after you click on logo (home) link. 

Allowing this without breaking the functionality we want wouldn't be easy (why I removed the label) and would probably require adding more mess & technical debt to something we definitely need to refactor.

 Also, maybe this was desired when implemented? I don't know. We want them to complete their profile and not go somewhere else (but in such a case it shouldn't be a clickable link, or there should be message).

Anyways, since it is low priority and shouldn't be fixed in isolation of an overall refactor (IMHO) maybe let's close this? I can refer to this in my other ticket as reference.

**Comment by eyturner** [comment] 2020-07-18 00:20
Just to add on to @joshmorel, in`RouteWithSubRoutes.js` the line causing the redirect is specifically for the case where the user is authenticated but hasn't created a profile. Clicking the logo actually does take the user to the home page, but the home page then immediately redirects to the create-profile page to ensure the user completes their profile setup. I think this is the intended behavior and this issue should be closed.

**Comment by idjevm** [comment] 2020-07-18 01:11
Well @joshmorel same idea here, but for the verify email/email sent pages, I think there on those pages, we should allow the user to click on the logo and go back home, but for this page, it is ok to not have this logo clickable, enforcing the user to complete their profile which is what we want. Closing this issue as this behavior is ok for this page. @manualzuru feel free to reopen if you think otherwise.

**Closed by idjevm** 2020-07-18 01:11 UTC
Labels: Desktop, Individual Profile, Low Priority, MVP - Release 1
