### ISSUE TITLE
GTM ID need fixes

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1642] opened 2020-10-12 15:49 UTC
**Please make sure the id attributes are updated for the mobile version as well!!**

Please assign the following elements with the listed JSX 'id' attributes.

Please also note, when assigning id attribute, to assign it to the area that encompasses the entire button or element (including any _clickable_ WHITE SPACE around text).
Example: not just the text "Next", but the entire button (including Next and arrow symbol)
<img width="150" alt="Screen Shot 2020-07-03 at 6 43 37 PM" src="https://user-images.githubusercontent.com/66695502/86501298-437b8c80-bd5d-11ea-929d-bffb689f5fc0.png">

### Path: /organisation/##### (where ### indicates org ID number)
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 1. | Email Icon | ORG_EM |

<img width="700" alt="Screen Shot 2020-10-12 at 10 41 32 AM" src="https://user-images.githubusercontent.com/66695502/95765484-9081cf80-0c77-11eb-8f57-12b19d66c879.png">

### Path:  /profile/##### and  /organisation/#####
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 2. | Upload Avatar Icon (Camera) - Individual Profile | PR_UA |
| 3. | Upload Avatar Icon (Camera) - Org Profile | ORG_UA |

<img width="197" alt="Screen Shot 2020-10-12 at 10 43 56 AM" src="https://user-images.githubusercontent.com/66695502/95765945-2d446d00-0c78-11eb-8b5b-c1795b5c8e24.png">

For ID not firing in GTM, please refer to this set of [instructions](https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255) on how to debug GTM tags in your local environment.

**Comment by idjevm** [comment] 2020-10-13 20:57
Closing this manually as I verified them locally. Feel free to reopen them after testing on staging if the problem persists. It works locally.

**Closed as completed by idjevm** 2020-10-13 20:57 UTC
Labels: FRONTEND, BI, Metrics, p_Profile/Account, P1 🔥

**Comment by rabbi08** [comment] 2020-10-14 00:13
@idjevm @Zaydme @joshmorel @doheekim93 
STG: 
I have following observation, please note these might not be an issue but still wanna highlight as a observation. Hence, kindly confirm, if this expected behavior if the GTM tag is not fired on the click, Also please note that for location filter, GTM tags are being fired as being shown in screenshots attached in PR# 1644

1. GTM tag is not FIRED while switching language or uploading profile or email icon is clicked. Refer below screen recording
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/67168400/95928302-075dbc00-0d8f-11eb-9162-ea7dfc1457da.gif)

2. While clicking on EMAIL icon for Org no ID, the Click ID is blank and GTM is not fired. refer below screenshot.
![OrgemalID](https://user-images.githubusercontent.com/67168400/95928070-7850a400-0d8e-11eb-92a4-4d45f1c1034c.png)

3.  After user upload image/avatar, the page is reloaded and the GTM summary all reset. Refer below GIF
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/67168400/95928757-404a6080-0d90-11eb-8c59-7a6d0ba681ca.gif)

Also, still to find the ID for upload icon ID for Org:
Click on camera icon -> and click 'Cancel' to cancel the upload process to avoid refresh. the Org ID is displayed. Refer below screenshot.

![OrgemalID](https://user-images.githubusercontent.com/67168400/95928667-fe211f00-0d8f-11eb-8b93-c1c2fe261340.png)

Thanks

**Comment by Zaydme** [comment] 2020-10-14 00:20
@rabbi08 please note the "Link click" is not the one that usually fires the GTM tag and the click id will be ""
Please check the "Click" that appears just after/before the "Link click".

Also some GTM tags might not show on the "Fired" section because they have not been added yet, to test just make sure you can see the "Click id"

**Comment by rabbi08** [comment] 2020-10-14 00:29
@Zaydme 
Oh, Agree, that was by mistake, I was referring CLICK only. Refer below screenshot
Ok and So as of now only the GTM tags fired are for location and Filter.

![image](https://user-images.githubusercontent.com/67168400/95929685-95877180-0d92-11eb-8799-3adb4ac65244.png)

**Comment by Zaydme** [comment] 2020-10-14 00:32
Yes, but it doesn't mean other tags aren't working, the ID is being detected, they are just not added on google tags manager yet.

**Comment by rabbi08** [comment] 2020-10-14 00:39
Verified the IDs for Individual & Org profile avatar but please note that the GTM summary resets after user upload an avatar as shown in the GIF as page refresh. Kindly confirm that the behavior is expected.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/67168400/95930414-6245e200-0d94-11eb-87a4-b902a9e88efb.gif)

Below are the screenshots of the IDs detected for the avatars:

Individual profile Avatar ID:
![Profile-avataar-GTM](https://user-images.githubusercontent.com/67168400/95930243-f794a680-0d93-11eb-98b1-2d13dad4f33d.png)

Org Profile avatar ID:
![OrgimageID](https://user-images.githubusercontent.com/67168400/95930255-ffece180-0d93-11eb-9cb4-ff9b05b0919f.png)

**Comment by Zaydme** [comment] 2020-10-14 00:43
@rabbi08 Yes, that's not a problem, because the event is sent to google once it's fired, and that will happen before the user selects, crops, and submits the avatar, and before the page refreshes.

**Comment by doheekim93** [comment] 2020-10-14 00:56
Hi @rabbi08, I just wanted to confirm what @Zaydme has said. The actual `tags` haven't been set up yet in GTM, which is why you won't see anything "firing up" in the Tags tab. However, the `Click ID`'s under the Variables tab are displaying the correct IDs, so we should be good. Also as @Zaydme mentioned, the information should be recorded on the button click event, so the page refresh and GTM resetting should be fine (but I can verify this with BI team as well).
