### ISSUE TITLE
Edit Profile-[Mobile Android]

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1066] opened 2020-07-07 20:55 UTC
Steps to create:
-Login with valid user name,password.
-Goto profile.
-Click on edit button.
-Select Edit profile.
-Half page is not displayed.
![Screenshot_20200707-164710_Chrome](https://user-images.githubusercontent.com/41587211/86842004-995c7700-c072-11ea-960a-52e2fb7e70f9.jpg)

**Comment by idjevm** [comment] 2020-07-07 21:13
Closing this one as it is a duplicate of #1021, please add more info to that issue instead.

**Closed by idjevm** 2020-07-07 21:13 UTC
Labels: Android, FRONTEND, bug, e2eTests
