### ISSUE TITLE
Staging/Prod Environment not working in IE Browser.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1304] opened 2020-07-31 00:14 UTC
Environment: https://staging.fightpandemics.work/
Browser:IE
![image (1)](https://user-images.githubusercontent.com/41587211/88986490-1f01ca00-d2a1-11ea-8de5-822e095bfb09.png)

**Comment by idjevm** [comment] 2020-07-31 00:21
Both environments don't load up on IE. I will be exploring this issue today and tomorrow and do a hotfix once the solution comes up!

**Comment by joshmorel** [comment] 2020-08-01 18:31
Thanks @sheeba1 FYI @idjevm . 

We don't support IE due to dependent libraries as well as how we implemented auth cookies. Basically we built this app on the assumption we would not support IE. Even Microsoft (as of 2019) says please don't use IE as a browser.

I discussed this at some earlier point, can't remember when, but we should display a plain text or simple html message that if they are running IE (of any version): "This browser is not supported, please use the latest version of  Edge, Chrome or Firefox".

Maybe conditional comments will work? https://htmldog.com/guides/html/advanced/conditionalcomments/

**Comment by joshmorel** [comment] 2020-08-01 18:34
@idjevm maybe change issue message to "Show browser not supported message for IE." Also not sure if this is really needed as a hotfix as I wouldn't consider it an urgent bug to fix.

Personally I think we should be releasing staging soon anyways to prod.

**Comment by phuclb** [comment] 2020-08-03 10:36
If not IE, can we test it on Edge?

I don't have experience in back-end or some front-end areas, but I don't know why this website couldn't work under IE (at least IE10+).

Hope in the future, we will find a way to support IE.

Here is Browser Market Share:
https://www.w3counter.com/globalstats.php

And our site is designed for all people in the world, and IE still takes an important part, I guess.

**Comment by joshmorel** [comment] 2020-08-17 15:44
Hi @phuclb Edge has been confirmed to work by others and definitely should be supported.

> but I don't know why this website couldn't work under IE (at least IE10+).

It's not trivial at this point as it was never considered from the start. We'd need to:

1. Implement polyfills for the libraries we depend and the libraries they depend on etc + maybe switch to other libraries if they do not support IE11 at all 
2. Change our method for secure persistent authentication
3. Add many styling rules so it doesn't look absolutely horrible 
4. And also test that it works "okay enough" on IE 

Even then there would be things that wouldn't work properly or well. It's a lot to take on for a volunteer team both from an implementation & maintenance perspectives. I'd say this would need to be prioritized against other desired features by the product team.

However to make that prioritization decision I think we'd need something more useful to go on than that chart. Maybe with GTM we could try to track the IP of someone who visits with IE11 then never comes back with another browser.

First things first though, we'd need some text to actually tell them such potential users this instead of just hanging. I'll create a new issue for this. I think we should close this ticket and product can re-assess about whether we want to support it.

**Closed as completed** 2020-08-29 00:51 UTC
Labels: bug, FRONTEND, P4, Josh

**Comment by joshmorel** [comment] 2020-08-29 00:53
I'm closing this as we have a resolution message wise.

We're not tracking stats as we'd need to setup GTM outside of react. We could but it seems like it would be way down on the priority of desired features.
