### ISSUE TITLE
The user should be able to sign up("Join Now") by pressing'Enter' key, after entering email and password and 'confirm password' fields

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1205] opened 2020-07-17 17:44 UTC
objective: The user should be able to sign up("Join Now") by pressing'Enter' key, after entering email and password and 'confirm password' fields

Actual behaviour: Need to click 'Join Now ' button to signup.

Expected: after entering email and password and 'confirm password' fields, the **'Join Now'** button should be enabled and user should be able to sign up , if the user press Enter key (same behaviour as FB)

**Comment by rabbi08** [comment] 2020-07-17 18:29
Duplicate of #787

**Comment by sheeba1** [comment] 2020-07-17 19:11
I came across similar issue with sign-up, so re-worded the original ticket as it was duplicate of #787

**Comment by adisen** [comment] 2020-07-18 11:21
This issue already exists. #787 and is being worked on at #937. So I'm gonna just close this.

**Closed by adisen** 2020-07-18 11:21 UTC
Labels: Desktop, MVP - Release 1, Mobile, e2eTests
