### ISSUE TITLE
Org POST are displayed as Individual POSTs

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#907] opened 2020-06-29 17:03 UTC
1. Open"https://staging.fightpandemics.work"
2. Login using valid email/pwd
3. Navigate to the Org Profile " Profile -> <Org_Name> [Already created & displayed under profile]
4. Click on 'Create Post' icon
5. Add Organization Post and Add new post

Issue: You will observe that POST is created with the profile logo/details of the respective Individual user NOT as a Organization from which is the POST is created. 
Also, it is displayed under 'My Activity' of Individual User not under 'My Activity' of the Organization.

Refer attached screen recording.
https://share.getcloudapp.com/E0uzgqbX

<img width="736" alt="image" src="https://user-images.githubusercontent.com/67168400/86034472-a9d47800-ba08-11ea-8771-b4704415843e.png">

**Comment by rabbi08** [comment] 2020-06-29 17:04
@vikjoshi

**Comment by joshmorel** [comment] 2020-06-29 18:43
@rabbi08 Strange I can't recreate it. Do the exact same and it's posted with the author as org. I'm going to ask in devops to see if I can troubleshoot some other way.

Somewhat related but more from a UX wise @vikjoshi @indirabhowmick do you think it makes sense if the picking the individual/org is skipped if I create a post from my profile.

Currently we can create a post from 3 places:

1. Feed - picking individual/organization makes sense
2. My own profile - should we just default to individual?
3. Profile of organization I own - should we just default to that organization?

**Comment by rabbi08** [comment] 2020-06-29 19:12
@joshmorel I am still able to reproduce the issue. Here another video of the steps, for reference, in case something from missed from written steps:

https://share.getcloudapp.com/Z4uY7ojB

**Comment by joshmorel** [comment] 2020-06-29 19:44
Thanks @rabbi08 I'll dig more into this.

**Comment by vikjoshi** [comment] 2020-06-29 19:47
Thanks @rabbi08 @joshmorel - yeah this would be good to fix. @joshmorel , guessing the issue @rabbi08  found is a back-end issue but let me know what you think after troubleshooting. 

For the UX question- agreed that it should default to individual if you're on the indiv profile and org. if you're on the org profile. That would be a nice to have but don't think we need to prioritize it for now

**Comment by joshmorel** [comment] 2020-06-29 20:21
Good call @vikjoshi we can create another issue for that. 

Truly, this might be F/E, B/E or infrastructure. I really can't tell yet. I'll ask a bit more in Slack.

**Comment by kylejvh** [comment] 2020-06-29 21:28
FWIW, I tried reproducing this as written and was also unable to reproduce.

**Comment by rabbi08** [comment] 2020-06-30 04:07
Currently me too unable to reproduce the issue. It looks as it was session error. Because I was testing with continue session from while back in my morning before the other organization merge, as I can now add new organization and no blank page is coming for the Organization profile page.

The Organization POST are displayed with Org Profile Details. as shown in below screenshot.

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/67168400/86082387-9d323d00-ba65-11ea-9ba1-7a71071de6b2.png">

**Comment by rabbi08** [comment] 2020-06-30 04:16
But, They are still NOT displayed under 'Profile -> Org_name -> My Activity'

Also, the profile logo is  different in the POST, i.e. while in Org Profile its T2 and on Post its only 'T', 
will log separate issue for that as I need more time to investigation around. 

Thnx

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/67168400/86082571-1893ee80-ba66-11ea-9812-7bf01834466a.png">

**Comment by vikjoshi** [comment] 2020-06-30 04:29
@rabbi08 , just FYI- @cvaldez98 is working on integrating posts/org profile so posts show up under "My Activity". It's logged here: https://github.com/FightPandemics/FightPandemics/issues/825

**Comment by vikjoshi** [comment] 2020-06-30 04:29
Also, I think we should close this ticket out unless someone sees this issue pop up again in the next few days

**Closed** 2020-06-30 04:35 UTC
Labels: MVP - Critical, Organization Profile, bug
