### ISSUE TITLE
Invalid redirection bug

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#757] opened 2020-06-20 08:40 UTC
Clicking on the feed redirects the user to login page.

Expected behaviour:
There should not be any involuntary redirection. I believe that this issue was fixed earlier but now has been reproduced.

Please refer to the gif below to replicate

![feedbug](https://user-images.githubusercontent.com/6276256/85197587-9be37080-b2ff-11ea-8ebc-1d05b1d25bcb.gif)

**Comment by joshmorel** [comment] 2020-06-20 16:14
I think the reason this is happening, is if you like a post while logged this is stored in session storage:

![image](https://user-images.githubusercontent.com/10546720/85206276-f6c09c00-b2ee-11ea-8a8b-717b0b32ac1b.png)

The app logic want's you to login, I guess to complete the like? The problem is now it will keep trying even if you navigate/refresh because the item is still in session storage.

@BMariscal when you work on comments API can you address this?

In the interim, @ppagarawal if you close your browser and re-open the Session Storage will be cleared and you can continue with other QA.

**Comment by joshmorel** [comment] 2020-06-21 15:16
@silenceway will this be resolved by finishing work related to liking/unliking posts? #761

**Comment by BMariscal** [comment] 2020-06-22 23:38
OH I just saw this @joshmorel I know the function where this is happening. I can take care of it.

**Closed** 2020-06-26 15:58 UTC
Labels: Feed, HomePage, MVP - Critical, bug
