### ISSUE TITLE
[Mobile-Android] Infomation provided in the initial flow is not populated in the filter.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1526] opened 2020-09-14 20:37 UTC
Environment -Staging
Device-Samsung Galaxy s8
Steps to create:
1.Click on Request Help.
2.Click on Medical.
3.Provide Address (ex:19020 Bensalem).
4.Skip Email.
Expected Result:
If we check the filter,the information provided should be updated .
Actual Result:
All the filter details are not updated such as location is blank ,Type (Medical is not enabled),Offer/Request help(Request help is not enabled)
![Screenshot_20200914-162125_Chrome](https://user-images.githubusercontent.com/41587211/93135457-5dfcab00-f6a8-11ea-98dc-80e704f47851.jpg)
![Screenshot_20200914-162149_Chrome](https://user-images.githubusercontent.com/41587211/93135473-63f28c00-f6a8-11ea-9cb5-12938f672dac.jpg)
![Screenshot_20200914-162154_Chrome](https://user-images.githubusercontent.com/41587211/93135483-681ea980-f6a8-11ea-82c8-caad9c926dac.jpg)

**Comment by nivetheatha** [comment] 2020-09-14 20:39
For the production only Request/Offer help is not enabled in filter.Other filters works fine.

**Comment by joshmorel** [comment] 2020-09-15 15:39
Thanks @nivetheatha 

The 1 issue (affecting desktop/mobile) was caused by #1519 & solved by #1528. Staging service might have been serving an old version to you as it was recently deploy. Can you check again and if it's okay close this issue. You may need to close your browser tab & re-open (the React code will still be the old code).

> For the production only Request/Offer help is not enabled in filter.Other filters works fine.

This seems to be an older issue affecting mobile only. Can we create a new ticket just for this?

**Comment by joshmorel** [comment] 2020-09-15 16:02
Resolved by #1528

**Closed as completed by joshmorel** 2020-09-15 16:02 UTC
Labels: bug, FRONTEND, Mobile Web
