### ISSUE TITLE
[Mobile] Feed | Create post "+" button is too small

### ISSUE THREAD

**Issue by hellynyc** [FightPandemics/FightPandemics#1134] opened 2020-07-13 04:25 UTC
Device/OS/Browser/Env: OnePlus 7 Pro / OS10 / Chrome 83 / Staging

Steps to Reproduce:
1. Log in and go to "Help Board"

![Screenshot_20200712-235754](https://user-images.githubusercontent.com/52841932/87270753-15a1f080-c49f-11ea-9d35-c1f6e0cbe338.jpg)

**Comment by idjevm** [comment] 2020-07-13 04:56
This is a duplicate of #1107, and it is not MVP - Critical. Please add more info to the mentioned issue. Thanks.

**Closed by idjevm** 2020-07-13 04:56 UTC
Labels: Feed, MVP - Critical, Mobile Web, bug, e2eTests
