### ISSUE TITLE
Desktop/Mobile web UI- Hide email address on View User profile screen when viewing other user's profile

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#655] opened 2020-06-09 03:59 UTC
- [ ] Hide email address on View User profile screen when viewing other user's profile
https://zpl.io/bWzjANx

**Comment by larryabim** [comment] 2020-06-09 22:49
Am I allowed access to zeplin so I can see the issue

**Comment by indirabhowmick** [comment] 2020-06-10 04:02
@larryabim - please request for access from @manualzuru 
@robinv85 - Tagging Robin since he is working on this feature.

**Comment by robinv85** [comment] 2020-06-12 18:49
@indirabhowmick I worked on the view profile for your own user, but we don't have support to view another user profile at the moment, and you can never see the email address.

**Comment by indirabhowmick** [comment] 2020-06-13 23:38
@robinv85 @larryabim - I agree with @robinv85 . We do not have the design for it. For now, when a user clicks on other user's profile, we can display the view profile page, but hide the email address. Nothing should be editable on that page. 
![image](https://user-images.githubusercontent.com/57240870/84581258-37bb2c80-ad94-11ea-9d87-d8ec9df3c714.png)

Tagging @Yu-Alexa-Zhao @manualzuru since we do not have a design for it.

**Comment by pthoma14** [comment] 2020-06-30 02:45
@joshmorel I see you mentioned this issue yesterday. Is this issue still open or should it be closed?

**Comment by pthoma14** [comment] 2020-06-30 16:04
@indirabhowmick is anyone assigned to this issue? Do you believe we can push this UI issue to the real MVP launch instead of the soft launch?

**Comment by indirabhowmick** [comment] 2020-06-30 16:08
@pthoma14 - functionality has already been implemented. @robinv85 @joshmorel @idjevm - Please confirm

**Comment by pthoma14** [comment] 2020-06-30 21:57
@indirabhowmick I've confirmed that this functionality is currently working.

**Comment by joshmorel** [comment] 2020-06-30 22:00
Yeah this one wasn't linked because it was the 2nd tagged after "Resolves" keyword

**Closed** 2020-06-30 21:59 UTC
Labels: Difficulty - Easy, FRONTEND, Individual Profile, MVP - Critical, Mobile Web

**Comment by pthoma14** [comment] 2020-06-30 22:01
Ahh got it. Thanks @joshmorel
