### ISSUE TITLE
Organisation Profile | Missing App store / Play store icons

### ISSUE THREAD

**Issue by hellynyc** [FightPandemics/FightPandemics#1315] opened 2020-08-03 04:12 UTC
Web: Chrome 84
Android: OnePlus 7 Pro
iOS: iPhone 6 Plus

Preconditions: User is logged in and has an organisation profile with links to App Store & Play Store

Steps to reproduce:
1. Go to the user's organisation profile

![Screen Shot 2020-08-02 at 11 55 18 PM](https://user-images.githubusercontent.com/52841932/89145072-90e64780-d51d-11ea-8037-ac914e8cc93b.png)

**Comment by idjevm** [comment] 2020-08-03 14:43
This is a duplicate of #1089, please any additional info there please.

**Closed as completed by idjevm** 2020-08-03 14:43 UTC
Labels: bug, FRONTEND, Organization Profile, Desktop, Mobile, e2eTests
