### ISSUE TITLE
Redirect a logged in user to the help board when he clicks on the logo

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#1271] opened 2020-07-26 08:11 UTC
As a logged in user, I want to be redirected to the Help Board when I click on the FightPandemics logo from any page.

For a non-logged in user, clicking on the FightPandemics logo will redirect them to the homepage.

**Comment by idjevm** [comment] 2020-07-26 08:16
I don't find that logic correct. The logo should redirect to one place, and one place only. We could redirect the user to either just the help board if logged in or to the sign-in page if not signed in. But makes no sense to have it to one place or the other based on authentication. We could implement it but is it really that what we want?

**Comment by idjevm** [comment] 2020-07-26 08:18
But then again, how will a signed in user get to the home page? or is the idea to have logged in users not have access to the home page + onboarding pages?

**Comment by ppagarawal** [comment] 2020-07-26 08:26
Home page and onboarding is for the user to get to know the platform and get onboarded. Once the onboarding is done, the user is not required to undergo a re-onboarding. He can access all the required features from the filters itself. For non-logged in user, it is reasonable to have him on the homepage because he would still be need to get familiar with the platform. Moreover, the design is such that he can always navigate to the sign up page.

**Comment by RF9A5V** [comment] 2020-08-11 14:40
Hey @idjevm and @ppagarawal,

The fix for this is in #1356. I'm assuming that this behavior is still desired because the issue is still open, but if not, let me know and close the issue.

**Comment by manualzuru** [comment] 2020-08-11 14:50
Yes @EyeWumbo this is still desired and it makes sense what @ppagarawal is proposing!

**Closed as completed** 2020-08-13 20:30 UTC
Labels: Desktop, Mobile Web, Platform
