### ISSUE TITLE
Symptoms check - steps 4 page opens white - text invisible

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#304] opened 2020-05-11 12:13 UTC
Env: https://staging.fightpandemics.work/symptoms-check
Steps:
1. Go to Symptoms checker
2. Click arrow and go to the Step 3. When Step 3 opens user sees the center of the text. Scrolling is necessary to see the beginning of the text. 
3. Scroll down and click the arrow. 
4. Step 4 page is open. User sees empty/white screen with two arrows (Please see attached screenshot). It's not intuitive. Scrolling is necessary to see the beginning of the text. 

![step 4](https://user-images.githubusercontent.com/21987083/81559953-b0dbf400-9390-11ea-9a67-0798cf184140.png)

More info:
Browser: Chrom v. 81 
mac os

**Comment by omarzoghayyer** [comment] 2020-05-15 21:07
@galeza It looks like you need to scroll up in order to see the content. So you are requesting to scroll up in default ?

**Comment by galeza** [comment] 2020-05-16 15:14
Is it possible to scroll? Currently it doesn't look good.

**Comment by omarzoghayyer** [comment] 2020-05-18 18:42
@galeza Yes, I can try and fix it.

**Comment by omarzoghayyer** [comment] 2020-05-21 18:44
Issue is been fixed on another branch. Also, the initial issue might have been associated the type of browser you are using. This issue will be closed for now.

**Comment by snowiesuet** [comment] 2020-05-21 19:16
This issue is caused by antd modal. It is currently taking the height of the content with the highest number of options and applied to all other modal, causing white space at the bottom. I'll investigate further in the future.

**Comment by manualzuru** [comment] 2020-06-23 00:29
@snowiesuet @omarzoghayyer are you still working on this?

**Comment by omarzoghayyer** [comment] 2020-06-23 05:17
@manualzuru I believe @snowiesuet wanted to work on it.

**Comment by Joeu** [comment] 2020-06-23 21:38
There are a lot of issues regarding the SymptomsCheck page, but I have a specific question about it. Right now the steps are held inside a modal, but in [zeplin](https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed0346a6f722bba0e0e6943) it is a normal page, should I remove the modal approach, @manualzuru , @galeza , @snowiesuet , @omarzoghayyer ?

**Comment by omarzoghayyer** [comment] 2020-06-27 03:54
@Joeu I am not 100% sure but i think the main cause of this issue is the modal approach. But i'd definitely check with @robinv85 first.

**Comment by Joeu** [comment] 2020-06-29 15:44
> @Joeu I am not 100% sure but i think the main cause of this issue is the modal approach. But i'd definitely check with @robinv85 first.

Yeah, @omarzoghayyer . That's why I need to know in which direction we should move (keeping or removing the modal).

**Comment by phuclb** [comment] 2020-07-30 06:56
This part has several issues to check:
1. Modal layout
2. Step layout
3. Button (Next/Back) issue

To resolve all things and make it works better, I suggest:
1. Update modal & step layout
2. Update all issues (if existed) in each step

I'm considering this issue to do.
Let me know if there's any feedback.

PS: It looks like this part is also missing some steps, reported in other issues.

**Comment by dhruvdpatel** [comment] 2020-08-21 00:43
This issue is not reproducible. Also, design bugs are addressed in other tickets. This can be closed.

**Closed by dhruvdpatel** 2020-08-21 00:43 UTC
Labels: FRONTEND, P3, bug, p_SymptomChecker
