### ISSUE TITLE
Navigating to any post -> Back on Help board: The users lands on the TOP of the Help board page rather than on the same post  from where user start.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1827] opened 2020-11-15 17:28 UTC
1. Open 'https://staging.fightpandemics.work/'
2. Navigate to Help Board -> add filter as 'provider ='Individual'
3. Scroll down and select/click any post to view/add comment to it -> Add comment -> Click 'Back' button

Issue: You will observe that user lands on the top of the Help Board page, ideally it should land on the same post/position after viewing the post. 
Refer below GIF.

![ezgif com-gif-maker (55)](https://user-images.githubusercontent.com/67168400/99191774-d7625980-273c-11eb-8fed-ea019c2a5390.gif)

Note: Tested both on desktop and mobile. This issue is related to #1709 
Also, Please note that filters are retained on the help board page after user navigate to other page and come BACK.

**Comment by Zaydme** [comment] 2020-11-15 18:09
I don't have the issue above, but I have another related one, when I refresh the feed page, I find myself at the end of the posts (end of "page" 1 ) and not at the top
![ezgif com-gif-maker](https://user-images.githubusercontent.com/46847212/99192947-09dc7880-2776-11eb-8dc5-5a943d016d75.gif)

**Comment by OzkanAbdullahoglu** [comment] 2020-11-16 07:25
@Zaydme I will check your founding too. I think It might be related to ScrollToTop component. 
@rabbi08 I couldn't reproduce your error. I landed in the right place. But I will investigate again in the first opportunity.

**Comment by OzkanAbdullahoglu** [comment] 2020-11-16 07:39
@Zaydme Okay, I think it is not a big deal. It is not about scrolltotop, I think I should do a better cleaning in router state. I'll check the code tonight.

**Comment by rabbi08** [comment] 2020-11-16 15:48
@OzkanAbdullahoglu 
I tried again on desktop and mobile, and it is NOT working. Please see GIF from mobile and desktop.

Mobile:
![ezgif com-video-to-gif 21](https://user-images.githubusercontent.com/67168400/99274888-d8f15780-27f8-11eb-9bc8-bdad73ab9acb.gif)


Desktop:
![ezgif com-gif-maker (57)](https://user-images.githubusercontent.com/67168400/99275161-2968b500-27f9-11eb-9584-012e56158ac6.gif)

**Comment by rabbi08** [comment] 2020-11-16 16:00
Rested the scenario for Andriod on simulation, it is NOT working.
- Even if you do NOT add filter:

![ezgif com-gif-maker (58)](https://user-images.githubusercontent.com/67168400/99276679-e3145580-27fa-11eb-84b3-40cdfdaab839.gif)

**Comment by OzkanAbdullahoglu** [comment] 2020-11-17 20:11
Hi,  this is for desktop, can I have a little help here? I couldn't reproduce the error in chrome, @Zaydme  what about you? 


![2020-11-17_23-07-27](https://user-images.githubusercontent.com/34690158/99442170-01c53a00-292a-11eb-9ad1-c7105adeba57.gif)

**Comment by Zaydme** [comment] 2020-11-17 20:23
@OzkanAbdullahoglu same, I am still unable to reproduce this issue, on both mobile and desktop.

**Comment by rabbi08** [comment] 2020-11-17 20:25
> Hi, this is for desktop, can I have a little help here? I couldn't reproduce the error in chrome, @Zaydme what about you?
> 
> ![2020-11-17_23-07-27](https://user-images.githubusercontent.com/34690158/99442170-01c53a00-292a-11eb-9ad1-c7105adeba57.gif)

I got the issue @OzkanAbdullahoglu 
The issues occur if user clicks on 'comment' -> add comment -> Back -> user does  NOT lands on same post on Help Board
But if user click on the post -> add comment -> Back -> user lands on the same post on help board

Refer below GIF.
![ezgif com-gif-maker (60)](https://user-images.githubusercontent.com/67168400/99443654-1af9c680-28e9-11eb-9bbf-337f0ea8f0fa.gif)

**Comment by OzkanAbdullahoglu** [comment] 2020-11-17 20:33
Yes, now I realised too. Finally 😌

**Comment by Zaydme** [comment] 2020-11-17 20:36
That makes so much sense now.

**Closed as completed** 2020-11-24 19:15 UTC
Labels: p_HelpBoard
