### ISSUE TITLE
New Organisation type and industry drop-down

### ISSUE THREAD

**Issue by lmpeixoto** [FightPandemics/FightPandemics#1469] opened 2020-08-29 14:24 UTC
When the user creates a new Organisation both the type and industry drop-downs don't show the complete text with smaller resolutions. Even when the option is selected the user can't see the complete text even when the mouse is over.

![cp_1](https://user-images.githubusercontent.com/43410947/91638993-4b794500-ea0b-11ea-8b82-a0fb5565353f.PNG)

![cp_2](https://user-images.githubusercontent.com/43410947/91639012-66e45000-ea0b-11ea-80de-ac79f1bbe82e.jpg)

**Comment by Serhazor** [comment] 2020-08-29 18:38
From the way it looks like on screenshot, it seems that it's cut cause of the length of the box with a drop down menu, will you be okay if the box length if extended by a bout a half?

**Comment by Serhazor** [comment] 2020-08-29 18:46
Can't recreate the issue as it seems that boxes are wide enough. @lmpeixoto can you check if the issue is still there?

![image](https://user-images.githubusercontent.com/44921903/91644037-54c8d880-ea30-11ea-816f-65ba9a1a544f.png)

**Comment by lmpeixoto** [comment] 2020-08-29 19:14
Yes Serhazor. If you start with a small window you only have one div... Here you have the drop-down perfectly sized.

![size1](https://user-images.githubusercontent.com/43410947/91644453-fdc50280-ea33-11ea-9a7b-4e51fdf4f3ec.png)

When you enlarge the window, just when you begin with two divs side by side, it's there when the boxes are small...

![size2](https://user-images.githubusercontent.com/43410947/91644479-3b299000-ea34-11ea-8594-1c11a9d25901.png)

**Comment by lmpeixoto** [comment] 2020-08-29 19:22
Resolution 1024x768 - Chrome (85.0.4183.83) Windows 10

**Comment by CamilaArias** [comment] 2020-08-30 00:53
@lmpeixoto I suppose whoever looks into this could also take a look at #1465 ?

**Comment by lmpeixoto** [comment] 2020-08-30 06:46
Yes sure @CamilaArias

**Comment by manualzuru** [comment] 2020-08-30 23:06
I agree the boxes should be definitely bigger. Currently is hard to read.

**Comment by rabbi08** [comment] 2021-01-03 19:18
This issue is no longer valid as the the 'Type' and 'Industry' dropdown' are fixed via #1465 . hence, closing this issue as od now, please open a new issue, if this issue is observed again. Thanks

**Closed as completed by rabbi08** 2021-01-03 19:18 UTC
Labels: good first issue, FRONTEND
