### ISSUE TITLE
View Community Postings screen link View More is disabled

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#266] opened 2020-05-07 12:52 UTC
env: https://staging.fightpandemics.work/feed

1. From main screen select View Community Posting link. View Community Postings screen is open.
2. Select View More link.
Link is disabled.

Should this link be enable for example for the first post on this page?

**Comment by omarzoghayyer** [comment] 2020-05-08 00:25
Ill work on this issue

**Comment by anniegiang** [comment] 2020-05-09 21:09
duplicate of https://github.com/FightPandemics/FightPandemics/issues/271

**Closed by anniegiang** 2020-05-09 21:09 UTC
Labels: Difficulty - Easy, FRONTEND
