### ISSUE TITLE
f_Profile/Account (Feature Pod- Avatar for Profiles)

### ISSUE THREAD

**Issue by SubhaSarojini** [FightPandemics/FightPandemics#1405] opened 2020-08-20 20:41 UTC
PM - Subha Srikumar, Krithiga Sundar Raj
Feature Link
https://www.notion.so/fightpandemics/Avatars-for-Profiles-e4af32c040c94035a041c76b3c9a1e97

**Comment by skrithiga** [comment] 2020-08-25 15:03
This is a duplicate of https://github.com/FightPandemics/FightPandemics/issues/715
@ashminbhandari will be working on the original issue #715

**Closed as completed** 2020-08-25 15:02 UTC
Labels: Individual Profile, Organization Profile, p_Profile/Account, P1 🔥
