### ISSUE TITLE
Onboarding flow small UI bugs, and Submit button size issue 

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#563] opened 2020-06-03 15:32 UTC
Please help fix the "Submit" button size to equalize to the email address field

![image](https://user-images.githubusercontent.com/6276256/83656487-3bed8a00-a5dd-11ea-878e-e74313a97ed3.png)

Comment/ping me for questions.

**Comment by ppagarawal** [comment] 2020-06-07 14:23
This issue seems to have come up again but with respect to size and alignment. 

![image](https://user-images.githubusercontent.com/6276256/83971139-44a0d180-a8f7-11ea-926c-979135d4e1f6.png)

**Comment by ppagarawal** [comment] 2020-06-07 19:39
Another image:

![image](https://user-images.githubusercontent.com/6276256/83978383-bcd1bc00-a924-11ea-8158-2839b39628c4.png)

**Comment by omarzoghayyer** [comment] 2020-06-10 06:17
@BMariscal Im not sure why I was unassigned on this issue. I was working on it since @ppagarawal reopened it, and I already have a PR open for it.

**Comment by Joeu** [comment] 2020-06-10 11:30
I'm assigning to you then, @omarzoghayyer , since you already have a PR fixing this.

**Comment by idjevm** [comment] 2020-06-12 04:40
Reopening this issue instead of creating a new one, the problem is still happening, so let's try to get it as it is on the design. 

Need help step 3 design:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed0378f0c4a0f97f183cf26

Offer help step 3 design: 
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed03866f134a6b47f0746c0

Right now we match neither of these designs, so we should iterate and try to get it there.

@Joeu  I know you were gonna work on this issue but Omar had started. But since this is a new iteration, can you take a look and see if the design can be matched? I know Omar has already started looking into other issues so it would be good to get another set of eyes on this one.

**Comment by idjevm** [comment] 2020-06-12 04:48
Also, I would want to know if in the need help we are trying to force the user by not giving it the chance to skip on step 3? or should both the `need help` and `offer help` be equal and have the option to skip (step 3 (email input) )? @manualzuru @galeza @ppagarawal ?

**Comment by idjevm** [comment] 2020-06-12 04:55
Some more context here: 
- [x] Create a skip button for the need-help page. It should look like the one similar to the one on the link https://staging.fightpandemics.work/offer-help#Step3
- [x] Skip must redirect the user to the feed.

**Comment by Joeu** [comment] 2020-06-12 11:31
Sure, @idjevm , but I'm seeing that we have already two PRs linked to this issue, and one of those is already merged.

**Comment by idjevm** [comment] 2020-06-12 12:03
Which ones are those PRs?

**Comment by Joeu** [comment] 2020-06-12 12:17
Taking this one per conversation with @idjevm .

**Comment by BMariscal** [comment] 2020-06-12 17:17
I'm so sorry @omarzoghayyer I don't recall doing this. I think what happened is that I checked out the issue on my phone and accidentally unassigned you.

**Comment by Joeu** [comment] 2020-06-12 19:00
Just pushed some code. Screenshots below:

![submitButton1](https://user-images.githubusercontent.com/1004896/84537263-cad96100-acc5-11ea-89eb-75e7396a5f1e.png)
![submitButton2](https://user-images.githubusercontent.com/1004896/84537269-cc0a8e00-acc5-11ea-95a9-900f1074bb05.png)
![submitButton3](https://user-images.githubusercontent.com/1004896/84537270-cc0a8e00-acc5-11ea-9154-b65d23676110.png)

**Comment by idjevm** [comment] 2020-06-12 19:46
- [ ] Add skip button to both Offer Help and Need Help flows, and the skip button should redirect to /feed.
- [ ] The size of the submit button should be the same as the container of the enter your email address.
- [ ] Submit button should initially be disabled and only become available once a correct email has been put in the field
- [ ] All the NEXT buttons should become white when hovered over the same as the Submit button for both Need Help and Offer Help

We will solve the above small bugs with this PR.

**Comment by galeza** [comment] 2020-06-12 20:01
@idjevm 
"Submit button should initially be disabled and only become available once a correct email has been put in the field"
- Could we add some error message. Something like "Email is required."

**Comment by idjevm** [comment] 2020-06-12 21:03
Yes! We will implement this as well! Thank you so much @galeza for pointing this out.

**Comment by Joeu** [comment] 2020-06-14 00:42
Hello, everyone.

Please, let me know what you think about those changes.
I just added some translation in the active state for the buttons, so the user can have some feedback when clicking, I'm also changing the colors on hover.
@idjevm , @galeza , I'll wait for your feedback before pushing those changes.

![wizardFlowChanges](https://user-images.githubusercontent.com/1004896/84582148-bd53d200-adbe-11ea-91b0-7d1ce7d1a31b.gif)

**Closed** 2020-06-14 15:52 UTC
Labels: Desktop, FRONTEND, Mobile, Onboarding
