### ISSUE TITLE
Clicking on profile avatar in Comments should redirect user to the profile page

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#968] opened 2020-07-02 20:07 UTC
For any posted comments, as a logged in user, clicking on the avatar of the author of the comment should take me to their profile (individual profile if the comment is made by an individual and org profile is the comment is made by an organization). 

Thoughts on whether we need this for MVP-Critical? @ppagarawal @manualzuru @indirabhowmick @pthoma14 ? What is the end goal of the user clicking on the profile of the commenter?

**Comment by manualzuru** [comment] 2020-07-03 15:18
We need this for soft launch. Without this is impossible to see who is commenting on your post and impossible to close the loop.

The goal is seeing who is offering/requesting you the resources, services.

**Comment by vikjoshi** [comment] 2020-07-03 19:48
@manualzuru clarification question on this- even if they view the profile that doesn’t close the loop right? There’s no email address or anything on the profile that they can reach out to. They see where the org or person is based and some of the basics we have on the profile but i don’t think that closes the loop.

**Comment by idjevm** [comment] 2020-07-03 20:45
Hey guys, please continue the conversation in #944, this is a duplicate of that issue. Feel free to add as many more comments as you can on #944.

**Closed by idjevm** 2020-07-03 20:45 UTC
Labels: Individual Profile, MVP - Critical, MVP - Release 1, Organization Profile, Post
