### ISSUE TITLE
All the existing post are not displayed to logged in user.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1676] opened 2020-10-20 04:26 UTC
1. Login into STG "https://staging.fightpandemics.work/"
2. Navigate to Help Board
3. Filter the results as:
Provider = 'Individual' & Requesting Help

You will observe that total 15 records are displayed (Test Data as of today 10/20)

4. Now login using valid username/pwd and navigate to Help Board.
Filter the results as:
Provider = 'Individual' & Requesting Help

You will observe that only 3 records are displayed (Test Data as of today 10/20)

Refer attached GIF.
![ezgif com-gif-maker (20)](https://user-images.githubusercontent.com/67168400/96540050-a04a7680-126a-11eb-8aa9-9eb30c7eaf0f.gif)

**Comment by Zaydme** [comment] 2020-10-20 07:15
@rabbi08 I don't think this is an issue, some posts have limited visibility, (example: "state only"). when you are not logged in, your location is unknown so no filters are applied on the posts, but when you login, all those posts with limited visibility will disappear because now we know your location and we can compare it with the post's visibility.

**Comment by rabbi08** [comment] 2020-10-20 15:25
> @rabbi08 I don't think this is an issue, some posts have limited visibility, (example: "state only"). when you are not logged in, your location is unknown so no filters are applied on the posts, but when you login, all those posts with limited visibility will disappear because now we know your location and we can compare it with the post's visibility.

Agree @Zayd, that visibility of the post may affect the post display for any user. But how it can be that if post has visibility as 'State' and it is displayed to non-logged in user everywhere regardless of IP filtering.

If post is visible to that respective state only, then it should be displayed on the help board of that state only irrespective of login. We cant display post irrespective of their visibility for non logged in users. 

Also, as per my initial understanding, the post on the Help Board are already sorted on the base of location/IP for non-logged in users. Please confirm.

**Comment by Zaydme** [comment] 2020-10-20 19:11
> Also, as per my initial understanding, the post on the Help Board are already sorted on the base of location/IP for non-logged in users. Please confirm.

@rabbi08 
No, this is not the case. there is no location/IP sort/filtering for non-logged in users, unless they applied a location filter.

**Comment by adorapham** [comment] 2020-10-21 01:18
@rabbi08 -please check out #1613 that is my note for Help Board Search

**Comment by Zaydme** [comment] 2020-10-22 19:36
@rabbi08 do we close this issue? as it is an expected behavior

**Comment by rabbi08** [comment] 2020-10-23 04:03
> @rabbi08 do we close this issue? as it is an expected behavior

surely we can close as of now, though little confusing. Need to do more research. will open new in case I found specific case related to this issue. Closed.

Thanks @Zaydme for the update.

**Closed as completed** 2020-10-23 04:03 UTC
Labels: p_HelpBoard, Post Filters
